### ISSUE TITLE
Bool gives different results on Cpanel::JSON::XS boolean from non-XS version

### ISSUE THREAD

**Issue by oschwald** [tobyink/p5-type-tiny-xs#5]
This outputs `1` with the pure Perl version and `q{}` with the XS version:

```
use Types::Standard qw( Bool )
use Cpanel::JSON::XS
say Bool->check(Cpanel::JSON::XS::true)
```

**Comment by oschwald** [comment]
I also find the Perl case more useful, but I could live with either as long as they were consistent.

**Comment by tobyink** [comment]
Fixed in 0.014.

**Comment by tobyink** [comment]
Hmm, the Moose documentation states:
> `Bool` accepts 1 for true, and undef, 0, or the empty string as false.

The lack of test cases in the Moose test suite for overloaded objects, plus the weird behaviour of `Bool` with overloaded objects, seems to indicate that the booleans of JSON::PP work mostly by luck.

Illustration of the weird behaviour I mean:

```
use 5.016;
use strict;
use warnings;

{
	package MyBool;
	use overload
		bool      => sub { !! $_[0][0] },
		'0+'      => sub {    $_[0][0] },
		'""'      => sub { [qw/false true/]->[$_[0][0]] },
		fallback  => 1,
	;
	our $FALSE = bless [0];
	our $TRUE  = bless [1];
}

{
	package MyClass;
	use Moose;
	has attr => (is => 'ro', isa => 'Bool');
}

# MyBool has pretty sane overloading but Moose's Bool rejects it.
MyClass->new(attr => $MyBool::TRUE);
```

Even though it's a boolean attribute, and MyBool overloads `bool`, Moose's type constraint uses the `""` overload to check whether it's valid.

Yet accepting *all objects that overload `bool`* seems like a mistake, because pretty much any class that does overloading will overload bool so that `if ($object)` doesn't throw an exception.

**Comment by tobyink** [comment]
Also, FYI the old XS version was really bad. It accepted overloaded objects for false values, but not for true values. (And Type::Tiny::XS is a fork of Mouse's type constraints, so I guess Mouse does the same.)
